GraphRegister
GraphRegister::GraphRegister(VertexIndex numQubits, int randomize=-1)
Instantiate a quantum register with 'numQubits' qubits, initally all in state |0>.
If randomize > -1 the RNG will be seeded with the current time plus the value of randomize. (Otherwise, it is not seeded.) That the value of randomize is added to the seed is useful in parallel processing settings where you want to ensure different seeds. (If you call this from Python, remember, that Python's RNG is not seeded.)
GraphRegister::GraphRegister(GraphRegister &gr)
Copy constructor.
Clones a register
GraphRegister::~GraphRegister()
void GraphRegister::local_op(VertexIndex v, LocCliffOp o)
Apply the local (i.e. single-qubit) operation o on vertex v.
References vertices.
Referenced by bitflip, hadamard, phaseflip, phaserot.
void GraphRegister::hadamard(VertexIndex v)
Apply a Hadamard gate on vertex v
References lco_H, local_op.
void GraphRegister::phaserot(VertexIndex v)
Apply a phaserot gate on vertex v. Phaserot means the gate S = |0><0| + i |1><1|.
References lco_S, local_op.
void GraphRegister::bitflip(VertexIndex v)
Apply a bitflip gate (i.e. a Pauli X) on vertex v
References lco_X, local_op.
void GraphRegister::phaseflip(VertexIndex v)
Apply a phaseflip gate (i.e. a Pauli Z) on vertex v
References lco_Z, local_op.
void GraphRegister::cphase(VertexIndex v1, VertexIndex v2)
Do a conditional phase gate between the two qubits.
void GraphRegister::cnot(VertexIndex vc, VertexIndex vt)
Do a controlled not gate between the vertices vc (control) and vt (target).
int GraphRegister::measure(VertexIndex v, LocCliffOp basis=lco_Z, bool *determined=NULL, int force=-1)
Measure qubit v in basis 'basis'.
Stabilizer & GraphRegister::get_full_stabilizer(void) const
Create the Stabilizer of the state.
This is useful to print out the stabilizer (or to compare with CHP). You can also use print_stabilizer.
void GraphRegister::invert_neighborhood(VertexIndex v)
Do a neighborhood inversion (i.e. local complementation) about vertex v.
void GraphRegister::print_adj_list(ostream &os=cout) const
Prints out the description of the current state.
in terms of adjacency lists of the graph and the VOps.
void GraphRegister::print_adj_list_line(ostream &os, VertexIndex i) const
Prints the line for Vertex i in the adjacency list representation of the state.
void GraphRegister::print_stabilizer(ostream &os=cout) const
Print the current state in stabilizer representation.
vector<QubitVertex> GraphRegister::vertices
This vector stores all the qubits, represented as QubitVertex objects. The index of the vector is usually taken as of type VertexIndex.
Referenced by local_op.
void GraphRegister::add_edge(VertexIndex v1, VertexIndex v2)
Add an edge to the graph underlying the state.
void GraphRegister::del_edge(VertexIndex v1, VertexIndex v2)
Delete an edge to the graph underlying the state.
void GraphRegister::toggle_edge(VertexIndex v1, VertexIndex v2)
Toggle an edge to the graph underlying the state.
(i.e. add it if not present, and delete it if present.)
int GraphRegister::graph_Z_measure(VertexIndex v, int force=-1)
Measure the bare graph state in the Z basis.
int GraphRegister::graph_Y_measure(VertexIndex v, int force=-1)
Measure the bare graph state in the Y basis.
int GraphRegister::graph_X_measure(VertexIndex v, bool *determined=NULL, int force=-1)
Measure the bare graph state in the X basis.
void GraphRegister::toggle_edges(const hash_set< VertexIndex > vs1, const hash_set< VertexIndex > vs2)
Toggles the edges between the vertex sets vs1 and vs2.
The function takes extra care not to invert an edge twice. If vs1 and vs2 are disjunct, this cannot happen and we do not need the function. If vs1 == v2s, we can do without, too.
bool GraphRegister::remove_byprod_op(VertexIndex v, VertexIndex use_not)
Do neighborhood inversions to reduce the VOp of vertex v to the identity.
void GraphRegister::cphase_with_table(VertexIndex v1, VertexIndex v2)
Use the cphase look-up table. This is called by cphase after VOps that do not commute with the cphase gate have been removed as far as possible.
ConnectionInfo GraphRegister::getConnectionInfo(VertexIndex v1, VertexIndex v2)
Check whether the qubits are connected to each other and to non-operand vertices.